[package]
name = "sony-bravia-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
serialport = {version = "4.2.2", default-features = false}
thiserror = "1.0.50"
